#!/usr/bin/env python3
"""
Migrate AWS Secrets Manager secrets to Supabase Vault
Keeps both - AWS remains as backup
"""

import subprocess
import json
import os

# Secrets to migrate (excluding revstar)
SECRETS_TO_MIGRATE = [
    "gbautomation/core/openai-api-key",
    "gbautomation/core/anthropic-api-key",
    "gbautomation/core/apify-api-token",
    "gbautomation/core/ref-tools-api-key",
    "gbautomation/infrastructure/supabase",
    "gbautomation/infrastructure/neo4j-graphiti",
    "gbautomation/infrastructure/langfuse",
    "gbautomation/aws/cli-default",
    "gbautomation/aws/langfuse-s3",
    "gbautomation/projects/gb-automation-landing/amplify",
    "gbautomation/supabase/unickqnwfheaczccvgbw/postgres_password",
    "gbautomation/core/google-ai-api-key",
    "gbautomation/core/jina-ai-api-key",
    "github-pat-gblack686",
    "gbautomation/core/linear-api-key",
    "claude-observability/anthropic",
    "core/api-key",
    "core-neo4j/credentials",
    "nih-github-pat",
    "gbautomation/core/youtube-api-key",
    "gbautomation/core/google-service-account",
    "gbautomation/core/apify-token",
    "gbautomation/integrations/telegram",
]

def get_aws_secret(secret_name):
    """Retrieve a secret from AWS Secrets Manager"""
    try:
        result = subprocess.run(
            ["aws", "secretsmanager", "get-secret-value",
             "--secret-id", secret_name,
             "--query", "SecretString",
             "--output", "text"],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error getting {secret_name}: {e.stderr}")
        return None

def aws_name_to_vault_name(aws_name):
    """Convert AWS secret name to Vault-friendly name"""
    # gbautomation/core/openai-api-key -> OPENAI_API_KEY
    # github-pat-gblack686 -> GITHUB_PAT_GBLACK686

    # Get the last part of the path
    if "/" in aws_name:
        parts = aws_name.split("/")
        # Use last part, or last two if meaningful
        if parts[-1] in ["aws", "supabase", "langfuse"]:
            name = "_".join(parts[-2:])
        else:
            name = parts[-1]
    else:
        name = aws_name

    # Convert to SCREAMING_SNAKE_CASE
    return name.upper().replace("-", "_").replace("/", "_")

def generate_vault_sql(secrets_data):
    """Generate SQL to insert secrets into Vault"""
    sql_statements = []

    for aws_name, secret_value, description in secrets_data:
        vault_name = aws_name_to_vault_name(aws_name)

        # Escape single quotes in secret value
        escaped_value = secret_value.replace("'", "''") if secret_value else ""
        escaped_desc = f"Migrated from AWS: {aws_name}".replace("'", "''")

        sql = f"SELECT vault.create_secret('{escaped_value}', '{vault_name}', '{escaped_desc}');"
        sql_statements.append((vault_name, sql))

    return sql_statements

def main():
    print("=" * 60)
    print("AWS Secrets Manager -> Supabase Vault Migration")
    print("=" * 60)
    print(f"\nSecrets to migrate: {len(SECRETS_TO_MIGRATE)}")
    print("\nFetching secrets from AWS...")

    secrets_data = []

    for secret_name in SECRETS_TO_MIGRATE:
        print(f"  Fetching: {secret_name}...")
        secret_value = get_aws_secret(secret_name)

        if secret_value:
            secrets_data.append((secret_name, secret_value, f"Migrated from AWS: {secret_name}"))
            print(f"    ✓ Retrieved")
        else:
            print(f"    ✗ Failed")

    print(f"\nSuccessfully retrieved: {len(secrets_data)} / {len(SECRETS_TO_MIGRATE)}")

    # Generate SQL
    print("\nGenerating Vault SQL statements...")
    sql_statements = generate_vault_sql(secrets_data)

    # Output SQL file
    output_file = os.path.join(os.path.dirname(__file__), "vault_migration.sql")
    with open(output_file, "w") as f:
        f.write("-- Supabase Vault Migration\n")
        f.write("-- Generated by migrate_aws_to_vault.py\n")
        f.write("-- Run this in Supabase SQL Editor\n\n")

        for vault_name, sql in sql_statements:
            f.write(f"-- {vault_name}\n")
            f.write(f"{sql}\n\n")

    print(f"\nSQL file written to: {output_file}")
    print("\nName mapping:")
    for aws_name, _, _ in secrets_data:
        vault_name = aws_name_to_vault_name(aws_name)
        print(f"  {aws_name} -> {vault_name}")

    return secrets_data

if __name__ == "__main__":
    main()
